
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";

// Interface for publication data - makes it easy to add new publications
interface Publication {
  id: number;
  title: string;
  authors: string;
  journal: string;
  year: number;
  link: string;
  abstract?: string;
  type: "publication" | "memo" | "preprint";
}

const Publications = () => {
  // Actual publications data from CV
  const [publications] = useState<Publication[]>([
    {
      id: 1,
      title: "Exploring Chroma Simulation Discrepancies: A Comparative Analysis of SolidWorks and Fusion360 Geometries",
      authors: "Daksh Bhatt, Sebastian Hofmann",
      journal: "PocaLab Internal Research Memo",
      year: 2024,
      link: "/lovable-uploads/baa395e8-ed1f-450d-b291-3f9b618ac5e9.png",
      abstract: "This report examines discrepancies in simulation results from 3D geometries created in SolidWorks and Fusion360. Despite using identical simulation parameters, variations were observed based on the software used and their settings. This report details the model creation, simulation setup, and execution workflow. Using 1,000,000 photons generated by the source, the comparative analysis highlights differences in numerical outcomes and graphical outputs, exploring potential reasons such as model creation and software-specific settings. The impact on experiment validity and reliability is discussed, leading to recommendations for eliminating these discrepancies.",
      type: "memo"
    }
  ]);

  return (
    <div className="min-h-screen pt-20 star-field">
      <div className="container mx-auto px-4 py-12">
        {/* Header Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-6xl font-bold text-cosmic mb-6">
            Publications & Research
          </h1>
          <p className="text-xl text-foreground/80 max-w-3xl mx-auto">
            Explore my research contributions to the field of astrophysics and computational physics.
          </p>
        </div>

        {/* Publications List */}
        <div className="max-w-4xl mx-auto space-y-8">
          {publications.map((publication) => (
            <Card key={publication.id} className="bg-card/30 backdrop-blur-sm border-border hover:bg-card/40 transition-all duration-300 animate-float">
              <CardContent className="p-6">
                <div className="space-y-4">
                  {/* Publication Type Badge */}
                  <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                      publication.type === 'publication' ? 'bg-primary/20 text-primary' :
                      publication.type === 'memo' ? 'bg-accent/20 text-accent' :
                      'bg-muted text-muted-foreground'
                    }`}>
                      {publication.type === 'memo' ? 'Internal Research Memo' : 
                       publication.type === 'preprint' ? 'Preprint' : 'Publication'}
                    </span>
                  </div>
                  
                  {/* Publication Title */}
                  <h2 className="text-2xl font-semibold text-cosmic hover:text-primary transition-colors">
                    {publication.title}
                  </h2>
                  
                  {/* Authors and Journal Info */}
                  <div className="text-foreground/70 space-y-1">
                    <p className="font-medium">{publication.authors}</p>
                    <p className="italic">{publication.journal} ({publication.year})</p>
                  </div>
                  
                  {/* Abstract */}
                  {publication.abstract && (
                    <p className="text-foreground/80 leading-relaxed">
                      {publication.abstract}
                    </p>
                  )}
                  
                  {/* Link to Paper */}
                  <div className="pt-4">
                    <Button 
                      asChild 
                      className="cosmic-gradient text-white hover:opacity-90 transition-opacity"
                    >
                      <a 
                        href={publication.link} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="inline-flex items-center"
                      >
                        <ExternalLink className="w-4 h-4 mr-2" />
                        {publication.type === 'memo' ? 'Read Memo' : 'Read Publication'}
                      </a>
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
          
          {/* Instructions for adding more publications */}
          <Card className="bg-card/20 backdrop-blur-sm border-border border-dashed">
            <CardContent className="p-6 text-center">
              <p className="text-foreground/60 italic">
                More publications coming soon as my research progresses.
                <br />
                This section will be updated with peer-reviewed publications and additional research outputs.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Publications;
